FROM mariadb:10.3
# ENV MYSQL_ROOT_PASSWORD test1357
ENV MYSQL_ALLOW_EMPTY_PASSWORD true
ENV MYSQL_DATABASE mydb
# COPY ./mysql_data/mysql /var/lib/mysql
EXPOSE 3306
# ENTRYPOINT ["mysqld", "--user=root"]
